name: Build Allure1

on: 
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: 'allure-framework/allure1'
          path: allure1
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Setup Allure Report
        run: | 
          wget https://repo1.maven.org/maven2/ru/yandex/qatools/allure/allure-commandline/1.5.4/allure-commandline-1.5.4-standalone.zip
          unzip allure-commandline-1.5.4-standalone.zip -d allure-commandline
          ./allure-commandline/bin/allure help
      - name: Generate Allure Report
        run: | 
          ./allure-commandline/bin/allure generate ./allure1/allure-model/src/test/resources/allure-results
      - name: Upload Allure Report
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report/
  deploy:
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4
