name: Build Allure1

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Setup Allure v1
        run: | 
          wget https://repo1.maven.org/maven2/ru/yandex/qatools/allure/allure-commandline/1.5.4/allure-commandline-1.5.4-standalone.zip
          unzip allure-commandline-1.5.4-standalone.zip -d allure1
          ./allure1/bin/allure help
